### ISSUE TITLE
Self-contained executable for hydromt_plugin as Fews-adapter

### ISSUE THREAD

**Issue by gijsber** [Deltares/deltaforge#6]
We want to the hydromt_delwaq plugin to act as Fews-adapter in a real-time system. In future a similar need is foreseen for hydromt_wflow (to accommodate landuse change scenarios).

From a Fews-perspective, it is not desired to do a deltaforge-install on the Forecasting Shell Servers. 
It is preferred that we have a self-contained executable which contains the necessary python packages and methods as used by the plugin (but no more than that).
We would like deltaforge to create this self-contained executable.

In our ideal world, we indicate the plugin for which we want an executable and the build script sorts out which packages are used by hydromt and the plugin.

Requested timeline: finished in February so it can be tested and improved as needed before we go live in Uruguay (around May)

**Comment by sibrenloos** [comment]
Thanks for the instant feedback!
I guess we want to avoid multiple distributions indeed. What I recall from the discussion with Peter is the idea to have a full Deltaforge rollout (creating the python environment) from which we @Deltares have the option to build a self-contained executable featuring one of the hydroMT-plugins that we like to use on a (FEWS) Forecasting Shell Server @Client and acts as a full model adapter (i.e. https://deltares.github.io/hydromt_delwaq/latest/_generated/hydromt_delwaq.DelwaqModel.setup_hydrology_forcing.html for the translation of WFlow output to Delwaq input).
But maybe it requires multiple distributions of DeltaForge? Let's have a live discussion soon (Jan2023)

**Comment by JoerivanEngelen** [comment]
What we discussed in a meeting today:

1. Hydro-MT Delwaq plugin will get a conda-forge release; @hboisgon will take care of this. See this issue https://github.com/Deltares/hydromt_delwaq/issues/13
3. It can then be included in Deltaforge. I will take care of this.
4. Test how to best call .exe from CLI, just like what we do in the CI. I will take care of this.
