### ISSUE TITLE
Create UI test scripts

### ISSUE THREAD

**Issue by gijsber** [Deltares/deltaforge#7]
Create test scripts (e.g. excel sheets) for the GUI distinguishing at least:
 Purpose, user action, expected behaviour, result (pass/fail), remark

Test scrips (populated for Projects page), empty exmaple for the rest, is available at:
n:\Projects\11208000\11208225\F. Other information\03 GUI\TestScripts\

**Comment by JoerivanEngelen** [comment]
@gijsber , I think you posted this issue in the wrong repository?

**Comment by gijsber** [comment]
@JoerivanEngelen , geen flauw idee hoe deze hier terecht kwam. ik heb hem vanuit het CST Toolbox project gecreerd
